### ISSUE TITLE
网络断开后，在恢复，reconnect陷入循环，未正常进行重连

### ISSUE THREAD

**Issue by happylhb** [mix-php/grpc#2]
客户端模式时，如果网络断开，重连会无效，导致while死循环
[$this->reconnect();](https://github.com/mix-php/grpc/blob/349a1dbbe39cf3350b8c70f6354d4be5b346bc28/src/Client.php#L78)

php环境
`php -v`
PHP 7.4.25 (cli) (built: Nov 13 2021 09:29:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

swoole环境
`php --ri swoole`

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.0
Built => Dec  1 2021 11:04:55
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1l  24 Aug 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by onanying** [comment]
while 中 reconnect() 如果没有网络，连接失败会  usleep(100000); // 0.1s ，直到网络成功恢复

**Comment by onanying** [comment]
应该是这里导致的问题 `strpos($this->client->errMsg, 'Broken pipe') !== false` ，你把你的那个 $this->client->errMsg 打印一下，复制粘贴出来

https://github.com/mix-php/grpc/blob/349a1dbbe39cf3350b8c70f6354d4be5b346bc28/src/Client.php#L171

**Comment by happylhb** [comment]
errCode:104
errMsg:Connection reset by peer

**Comment by onanying** [comment]
@happylhb  你可以手动先把 `&& strpos($this->client->errMsg, 'Broken pipe') !== false` 移除，我后面再发布新版本，其实这里任何错误都重连一下也没啥问题

**Comment by onanying** [comment]
@happylhb https://github.com/mix-php/grpc/commit/d37f3c639a9496f2dcc07c24d75913b83c6efb07 composer 升级 mix/grpc 到 v3.0.8
